/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_mango_demo__case_native2_NativeTest */

#ifndef _Included_org_mango_demo__case_native2_NativeTest
#define _Included_org_mango_demo__case_native2_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mango_demo__case_native2_NativeTest
 * Method:    add
 * Signature: (II)Ljava/lang/Integer;
 */
JNIEXPORT jint JNICALL Java_org_mango_demo__1case_native2_NativeTest_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
